#!/bin/bash

STAGED_FILES=$(git diff --diff-filter=d --staged --name-only)

# 変更・追加されたSwiftファイルをループ
echo "$STAGED_FILES" | grep -e '\(.*\).swift$' | while read -r file; do
  # SwiftFormatとSwiftLint autocorrect
  PROJECT_SWIFT_VERSION="$(cat .swiftversion)" ./bin/format.swift -p "${file}"
  # // MARK: - {Protocolなど} を自動的に追加
  ./bin/auto-add-mark.swift --path "${file}"
done
