# SwiftLint自動修正設定
# .swiftlint.ymlと整合性を保つ

included:
  - Packages

excluded:
  - Packages/*/.build
  - Packages/Mocks/Sources/Generated

only_rules:
  # 空白・改行
  - closing_brace
  - closure_spacing
  - colon
  - comma
  - leading_whitespace
  - opening_brace
  - operator_usage_whitespace
  - return_arrow_whitespace
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - vertical_whitespace

  # 冗長なコード
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - joined_default_parameter
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - void_return

  # レガシーAPI
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions

  # その他
  - mark
  - nimble_operator
  - number_separator
  - protocol_property_accessors_order
  - trailing_comma

  # .swiftlint.ymlで有効なルール（自動修正対応）
  - sorted_imports
  - redundant_self_in_closure
  - shorthand_optional_binding
  - prefer_self_in_static_references
  - direct_return
  - toggle_bool

colon:
  flexible_right_spacing: true
