disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - variable_name
  - file_length
  - type_body_length
included:
  - PriconneDB
excluded:
  - Carthage
  - Pods
large_tuple: 3
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
function_body_length: 100
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# force_cast: warning
force_try:
  severity: warning
